orbs:
  golangci-lint: timakin/golangci-lint@0.1.1
  go: circleci/go@1.7.1

version: 2.1

jobs:
  lint-and-test:
    executor:
      name: go/default
      tag: '1.19'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - run:
          command: |
            go install golang.org/x/tools/cmd/goimports@latest
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2
      - go/save-cache
      - run:
          command: |
            misc/cicd/code-lint.sh
      - go/test:
          failfast: true
          verbose: true

/extra/other/go-auxiliaries/selenium/:
  circleci/config:
    yml:

workflows:
  ci:
    jobs:
      - lint-and-test
